site_name: Clientele
site_url: https://docs.clientele.dev
theme:
  name: material
  favicon: favicon.png
  logo: favicon.png
  features:
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_name: phalt/clientele
repo_url: https://github.com/phalt/clientele
nav:
  - ⚜️ Home: index.md
  - 🚀 Install:
    - Install: install.md
  - 📕 Documentation:
    - Documentation: api-overview.md
    - 🎪 Examples: api-examples.md
    - ⚙️ Configuration: api-configuration.md
    - 🔀 Async Support: api-async.md
    - 🔐 Authentication: api-authentication.md
    - 🔌 HTTP Backends: api-http-backends.md
    - 💾 Caching: api-cache.md
    - 🌊 Streaming: api-stream.md
    - 🧬 GraphQL: api-graphql.md
    - 🚨 Exception Handling: api-exceptions.md
    - 🔄 Retries: api-retries.md
    - 🪵 Logging: api-logging.md
    - 🧪 Testing: api-testing.md
    - 🎯 Direct requests: api-direct-requests.md
    - 💉 Injected parameters & typing: injected-parameters.md
  - 📟 Command line tools:
    - 🏗️ Client creator: openapi-cli.md
  - ⚡️ API Server Integrations:
    - ⚡️ FastAPI: server-fastapi.md
    - 🦄 Django REST Framework: server-drf.md
    - 🥷 Django Ninja: server-django-ninja.md
  - 📝 Change Log: CHANGELOG.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
